on: [push, workflow_dispatch]

jobs:
  implement:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: yes

      - name: Set PDK
        run: |
          echo "PDK_ROOT={{ github.workspace }}/pdk" >> $GITHUB_ENV
          echo "PDK=ihp-sg13g2" >> $GITHUB_ENV

      - name: Run librelane
        uses: fossi-foundation/librelane-action@v0.1
        with:
          branch: leo/padring
          arguments: --manual-pdk --run-tag croc_pl_60_2100 --overwrite config.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            runs/

jobs:
  simulate:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true # Not recursive, to avoid cloning the PDK
      - name: Download simulator
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: simulation

      - name: Build simulator
        uses: fossi-foundation/verilator-action@v0.3
        with:
          working-directory: simulation
          run: 'make build-verilator'

      - name: Run simulator
        uses: fossi-foundation/verilator-action@v0.3
        with:
          working-directory: simulation
          run: 'make sim-verilator'